version: '3.8'

services:
  # --------------------------
  # RabbitMQ
  # --------------------------
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-net
  # --------------------------
  # Redis
  # --------------------------
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - kafka-net

  # --------------------------
  # RedisInsight
  # --------------------------
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "${REDISINSIGHT_PORT}:5540"
    depends_on:
      - redis
    networks:
      - kafka-net

volumes:
  redis_data:
  rabbitmq_data:

networks:
  app-net:
    driver: bridge
