spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

kafka:
  bootstrap-servers: ${KAFKA_SERVERS}

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: WARN
    com.fivefy: INFO

### 포트원 ###
portone:
  # 포트원 콘솔 > 결제연동 > V2 API Secret
  api-secret: ${PORTONE_API_SECRET}
  # 포트원 콘솔 > 연동 정보 > 상점 ID
  store-id: ${PORTONE_STORE_ID}
  # 포트원 API Url
  api-url: ${PORTONE_API_URL}
  channel-key: ${PORTONE_CHANNEL_KEY}
  # 웹훅 시크릿 키
  webhook-secret: ${PORTONE_WEBHOOK_SECRET}
  # 빌링키
  channel-key-billing: ${PORTONE_CHANNEL_KEY_BILLING}
