spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 2000ms

kafka:
  bootstrap-servers: ${KAFKA_SERVERS}

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: WARN
    com.fivefy: INFO

portone:
  api-secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}
  api-url: ${PORTONE_API_URL}
  channel-key: ${PORTONE_CHANNEL_KEY}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET}
